// Bump this whenever the content below changes (new/renamed utilities,
// corrected notes, etc.) — shown in the UI and used as JSON-LD dateModified.
export const LAST_UPDATED = "2026-09-04";

export type CheatEntry = {
  class: string;
  description: string;
};

export type CheatGroup = {
  title: string;
  slug: string;
  entries: CheatEntry[];
};

export type BreakingChange = {
  from: string;
  to: string;
  note?: string;
};

// Sourced from the official Tailwind CSS v4 upgrade guide (tailwindcss.com/docs/upgrade-guide).
export const V4_BREAKING_CHANGES: BreakingChange[] = [
  { from: "shadow-sm", to: "shadow-xs" },
  { from: "shadow", to: "shadow-sm" },
  { from: "drop-shadow-sm", to: "drop-shadow-xs" },
  { from: "drop-shadow", to: "drop-shadow-sm" },
  { from: "blur-sm", to: "blur-xs" },
  { from: "blur", to: "blur-sm" },
  { from: "backdrop-blur-sm", to: "backdrop-blur-xs" },
  { from: "backdrop-blur", to: "backdrop-blur-sm" },
  { from: "rounded-sm", to: "rounded-xs" },
  { from: "rounded", to: "rounded-sm" },
  { from: "outline-none", to: "outline-hidden" },
  { from: "ring", to: "ring-3", note: "default ring width is now 1px, not 3px" },
  { from: "flex-shrink-*", to: "shrink-*" },
  { from: "flex-grow-*", to: "grow-*" },
  { from: "overflow-ellipsis", to: "text-ellipsis" },
  { from: "decoration-slice", to: "box-decoration-slice" },
  { from: "decoration-clone", to: "box-decoration-clone" },
  { from: "bg-opacity-*", to: "bg-black/50", note: "opacity modifiers replace all *-opacity-* utilities" },
  { from: "text-opacity-*", to: "text-black/50" },
  { from: "border-opacity-*", to: "border-black/50" },
  { from: "ring-opacity-*", to: "ring-black/50" },
  { from: "!flex", to: "flex!", note: "important modifier moved to the end of the class" },
  { from: "bg-[--brand]", to: "bg-(--brand)", note: "arbitrary CSS variable syntax" },
  {
    from: "grid-cols-[max-content,auto]",
    to: "grid-cols-[max-content_auto]",
    note: "commas in arbitrary values become underscores",
  },
];

export const CHEATSHEET_GROUPS: CheatGroup[] = [
  {
    title: "Layout",
    slug: "layout",
    entries: [
      { class: "container", description: "Fixed max-width at each breakpoint" },
      { class: "block / inline-block / inline", description: "display" },
      { class: "flex / inline-flex", description: "display: flex" },
      { class: "grid / inline-grid", description: "display: grid" },
      { class: "hidden", description: "display: none" },
      { class: "aspect-square / aspect-video / aspect-[4/3]", description: "aspect-ratio" },
      { class: "columns-2 ... columns-12", description: "column-count" },
      { class: "break-after-column / break-before-page / break-inside-avoid", description: "CSS fragmentation breaks" },
      { class: "box-border / box-content", description: "box-sizing" },
      { class: "float-left / float-right / float-none", description: "float" },
      { class: "clear-left / clear-right / clear-both", description: "clear" },
      { class: "isolate / isolation-auto", description: "isolation (stacking context)" },
      { class: "object-cover / object-contain / object-fill / object-none", description: "object-fit" },
      { class: "object-center / object-top / object-left-bottom", description: "object-position" },
      { class: "overflow-auto / overflow-hidden / overflow-scroll / overflow-visible", description: "overflow (also overflow-x-*, overflow-y-*)" },
      { class: "overscroll-auto / overscroll-contain / overscroll-none", description: "overscroll-behavior" },
      { class: "static / fixed / absolute / relative / sticky", description: "position" },
      { class: "inset-0 / top-4 / right-2 / bottom-0 / left-1/2", description: "top / right / bottom / left" },
      { class: "visible / invisible / collapse", description: "visibility" },
      { class: "z-0 ... z-50 / z-auto / -z-10", description: "z-index" },
    ],
  },
  {
    title: "Flexbox & Grid",
    slug: "flexbox-grid",
    entries: [
      { class: "flex-row / flex-row-reverse / flex-col / flex-col-reverse", description: "flex-direction" },
      { class: "flex-wrap / flex-wrap-reverse / flex-nowrap", description: "flex-wrap" },
      { class: "flex-1 / flex-auto / flex-initial / flex-none", description: "flex shorthand" },
      { class: "grow / grow-0", description: "flex-grow (was flex-grow-* in v3)" },
      { class: "shrink / shrink-0", description: "flex-shrink (was flex-shrink-* in v3)" },
      { class: "basis-0 / basis-1/2 / basis-full / basis-64", description: "flex-basis" },
      { class: "order-1 ... order-12 / order-first / order-last / -order-1", description: "order" },
      { class: "grid-cols-1 ... grid-cols-12 / grid-cols-none", description: "grid-template-columns" },
      { class: "col-span-2 / col-start-3 / col-end-5 / col-auto", description: "grid-column placement" },
      { class: "grid-rows-1 ... grid-rows-6", description: "grid-template-rows" },
      { class: "row-span-2 / row-start-1 / row-end-3", description: "grid-row placement" },
      { class: "grid-flow-row / grid-flow-col / grid-flow-dense", description: "grid-auto-flow" },
      { class: "auto-cols-auto / auto-cols-min / auto-cols-fr", description: "grid-auto-columns" },
      { class: "auto-rows-auto / auto-rows-min / auto-rows-fr", description: "grid-auto-rows" },
      { class: "gap-4 / gap-x-2 / gap-y-6", description: "gap between flex/grid items" },
      { class: "justify-start / justify-center / justify-between / justify-evenly", description: "justify-content" },
      { class: "justify-items-start / justify-items-center / justify-items-stretch", description: "justify-items" },
      { class: "justify-self-auto / justify-self-end", description: "justify-self" },
      { class: "content-center / content-between / content-stretch", description: "align-content" },
      { class: "items-start / items-center / items-baseline / items-stretch", description: "align-items" },
      { class: "self-auto / self-center / self-stretch", description: "align-self" },
      { class: "place-content-center / place-items-center / place-self-center", description: "place-* shorthands" },
    ],
  },
  {
    title: "Spacing",
    slug: "spacing",
    entries: [
      { class: "p-4 / px-4 / py-4 / pt-4 / pr-4 / pb-4 / pl-4", description: "padding (all sides / axis / single side)" },
      { class: "ps-4 / pe-4", description: "padding-inline-start / padding-inline-end (logical)" },
      { class: "m-4 / mx-auto / my-4 / mt-4 / -mt-4", description: "margin (negative values allowed with -)" },
      { class: "ms-4 / me-4", description: "margin-inline-start / margin-inline-end (logical)" },
      { class: "space-x-4 / space-y-4", description: "gap between direct children (adds margin between siblings)" },
      { class: "space-x-reverse", description: "reverses the direction spacing is applied" },
      {
        class: "0, px, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 72, 80, 96",
        description: "default spacing scale (1 unit = 0.25rem = 4px, so p-4 = 1rem)",
      },
    ],
  },
  {
    title: "Sizing",
    slug: "sizing",
    entries: [
      { class: "w-4 / w-1/2 / w-full / w-screen / w-fit / w-min / w-max", description: "width" },
      { class: "min-w-0 / min-w-full / min-w-fit", description: "min-width" },
      { class: "max-w-xs ... max-w-7xl / max-w-full / max-w-prose / max-w-none", description: "max-width" },
      { class: "h-4 / h-1/2 / h-full / h-screen / h-dvh / h-svh / h-lvh", description: "height (dvh/svh/lvh = dynamic/small/large viewport units)" },
      { class: "min-h-0 / min-h-screen / min-h-full", description: "min-height" },
      { class: "max-h-full / max-h-screen", description: "max-height" },
      { class: "size-4 / size-full / size-1/2", description: "sets width and height together" },
    ],
  },
  {
    title: "Typography",
    slug: "typography",
    entries: [
      { class: "font-sans / font-serif / font-mono", description: "font-family" },
      { class: "text-xs ... text-9xl", description: "font-size (each step sets a matching line-height)" },
      { class: "antialiased / subpixel-antialiased", description: "font-smoothing" },
      { class: "italic / not-italic", description: "font-style" },
      { class: "font-thin ... font-black", description: "font-weight (100-900)" },
      { class: "tracking-tighter ... tracking-widest", description: "letter-spacing" },
      { class: "leading-none ... leading-loose / leading-4 ... leading-10", description: "line-height" },
      { class: "line-clamp-1 ... line-clamp-6 / line-clamp-none", description: "truncate text to N lines" },
      { class: "list-none / list-disc / list-decimal", description: "list-style-type" },
      { class: "list-inside / list-outside", description: "list-style-position" },
      { class: "text-left / text-center / text-right / text-justify", description: "text-align" },
      { class: "text-red-500 / text-black/50", description: "text color (with opacity modifier)" },
      { class: "underline / overline / line-through / no-underline", description: "text-decoration-line" },
      { class: "decoration-red-500 / decoration-2 / decoration-wavy", description: "text-decoration color / thickness / style" },
      { class: "underline-offset-4", description: "text-underline-offset" },
      { class: "uppercase / lowercase / capitalize / normal-case", description: "text-transform" },
      { class: "truncate / text-ellipsis / text-clip", description: "text-overflow" },
      { class: "text-wrap / text-nowrap / text-balance / text-pretty", description: "text-wrap" },
      { class: "indent-4 / -indent-4", description: "text-indent" },
      { class: "align-baseline / align-top / align-middle / align-bottom", description: "vertical-align" },
      { class: "whitespace-normal / whitespace-nowrap / whitespace-pre-wrap", description: "white-space" },
      { class: "break-normal / break-words / break-all / break-keep", description: "word-break / overflow-wrap" },
      { class: "hyphens-none / hyphens-manual / hyphens-auto", description: "hyphens" },
      { class: "content-none / content-['*']", description: "content (for ::before / ::after)" },
      { class: "text-shadow-2xs ... text-shadow-lg / text-shadow-none", description: "text-shadow (new utility in v4)" },
    ],
  },
  {
    title: "Backgrounds",
    slug: "backgrounds",
    entries: [
      { class: "bg-fixed / bg-local / bg-scroll", description: "background-attachment" },
      { class: "bg-clip-border / bg-clip-padding / bg-clip-content / bg-clip-text", description: "background-clip" },
      { class: "bg-red-500 / bg-transparent / bg-black/25", description: "background-color (with opacity modifier)" },
      { class: "bg-none / bg-linear-to-r / bg-radial / bg-conic", description: "background-image / gradients" },
      { class: "from-cyan-500 via-blue-500 to-indigo-500", description: "gradient color stops" },
      { class: "bg-origin-border / bg-origin-padding / bg-origin-content", description: "background-origin" },
      { class: "bg-center / bg-top / bg-[center_top_1rem]", description: "background-position" },
      { class: "bg-repeat / bg-no-repeat / bg-repeat-x / bg-repeat-y", description: "background-repeat" },
      { class: "bg-auto / bg-cover / bg-contain", description: "background-size" },
    ],
  },
  {
    title: "Borders",
    slug: "borders",
    entries: [
      { class: "rounded-xs ... rounded-3xl / rounded-full", description: "border-radius (v4: rounded-sm→rounded-xs, rounded→rounded-sm)" },
      { class: "rounded-t-lg / rounded-tl-lg", description: "border-radius per side / corner" },
      { class: "border / border-2 / border-t / border-x-4", description: "border-width (default border color is currentColor in v4)" },
      { class: "border-red-500 / border-black/50", description: "border-color" },
      { class: "border-solid / border-dashed / border-dotted / border-none", description: "border-style" },
      { class: "divide-x / divide-y / divide-red-500", description: "border between children" },
      { class: "outline / outline-2 / outline-offset-2", description: "outline-width / outline-offset" },
      { class: "outline-red-500", description: "outline-color" },
      { class: "outline-hidden / outline-none / outline-dashed", description: "outline-style (v4: outline-none→outline-hidden keeps focus ring for a11y)" },
    ],
  },
  {
    title: "Effects",
    slug: "effects",
    entries: [
      { class: "shadow-xs ... shadow-2xl / shadow-none", description: "box-shadow (v4: shadow-sm→shadow-xs, shadow→shadow-sm)" },
      { class: "shadow-red-500/50", description: "colored box-shadow" },
      { class: "opacity-0 ... opacity-100", description: "opacity" },
      { class: "mix-blend-multiply / mix-blend-screen / mix-blend-overlay", description: "mix-blend-mode" },
      { class: "bg-blend-multiply / bg-blend-overlay", description: "background-blend-mode" },
      { class: "mask-clip-border / mask-origin-padding", description: "mask-clip / mask-origin" },
      { class: "mask-linear-to-r / mask-radial / mask-[<url>]", description: "mask-image utilities" },
    ],
  },
  {
    title: "Filters",
    slug: "filters",
    entries: [
      { class: "blur-xs ... blur-3xl / blur-none", description: "filter: blur (v4: blur-sm→blur-xs, blur→blur-sm)" },
      { class: "brightness-50 ... brightness-200", description: "filter: brightness" },
      { class: "contrast-50 ... contrast-200", description: "filter: contrast" },
      { class: "drop-shadow-xs ... drop-shadow-2xl", description: "filter: drop-shadow (v4 renamed, see blur)" },
      { class: "grayscale / grayscale-0", description: "filter: grayscale" },
      { class: "hue-rotate-90 / -hue-rotate-90", description: "filter: hue-rotate" },
      { class: "invert / invert-0", description: "filter: invert" },
      { class: "saturate-50 ... saturate-200", description: "filter: saturate" },
      { class: "sepia / sepia-0", description: "filter: sepia" },
      { class: "backdrop-blur-xs ... backdrop-blur-3xl", description: "backdrop-filter: blur (v4 renamed, see blur)" },
      { class: "backdrop-brightness-50 / backdrop-contrast-125 / backdrop-opacity-50", description: "other backdrop-filter utilities" },
    ],
  },
  {
    title: "Tables",
    slug: "tables",
    entries: [
      { class: "border-collapse / border-separate", description: "border-collapse" },
      { class: "border-spacing-2 / border-spacing-x-2", description: "border-spacing" },
      { class: "table-auto / table-fixed", description: "table-layout" },
      { class: "caption-top / caption-bottom", description: "caption-side" },
    ],
  },
  {
    title: "Transitions & Animation",
    slug: "transitions-animation",
    entries: [
      { class: "transition / transition-all / transition-colors / transition-none", description: "transition-property" },
      { class: "duration-75 ... duration-1000", description: "transition-duration" },
      { class: "ease-linear / ease-in / ease-out / ease-in-out", description: "transition-timing-function" },
      { class: "delay-75 ... delay-1000", description: "transition-delay" },
      { class: "animate-spin / animate-ping / animate-pulse / animate-bounce / animate-none", description: "animation presets" },
    ],
  },
  {
    title: "Transforms",
    slug: "transforms",
    entries: [
      { class: "scale-0 ... scale-150 / scale-x-50 / scale-y-50", description: "scale" },
      { class: "rotate-0 ... rotate-180 / -rotate-45", description: "rotate" },
      { class: "translate-x-4 / -translate-y-1/2", description: "translate" },
      { class: "skew-x-6 / skew-y-3", description: "skew" },
      { class: "origin-center / origin-top-left", description: "transform-origin" },
      { class: "transform-none / transform-gpu", description: "force / disable hardware acceleration" },
      { class: "perspective-dramatic / perspective-none", description: "perspective" },
      { class: "backface-visible / backface-hidden", description: "backface-visibility" },
    ],
  },
  {
    title: "Interactivity",
    slug: "interactivity",
    entries: [
      { class: "accent-red-500", description: "accent-color (checkboxes, radios, range inputs)" },
      { class: "appearance-none / appearance-auto", description: "appearance" },
      { class: "caret-red-500", description: "caret-color" },
      { class: "cursor-pointer / cursor-not-allowed / cursor-wait / cursor-grab", description: "cursor" },
      { class: "field-sizing-content / field-sizing-fixed", description: "field-sizing (auto-growing textareas)" },
      { class: "pointer-events-none / pointer-events-auto", description: "pointer-events" },
      { class: "resize / resize-none / resize-x / resize-y", description: "resize" },
      { class: "scroll-auto / scroll-smooth", description: "scroll-behavior" },
      { class: "scroll-m-4 / scroll-p-4", description: "scroll-margin / scroll-padding" },
      { class: "snap-start / snap-center / snap-x / snap-mandatory", description: "scroll-snap utilities" },
      { class: "touch-auto / touch-none / touch-pan-x", description: "touch-action" },
      { class: "select-none / select-text / select-all / select-auto", description: "user-select" },
      { class: "will-change-auto / will-change-scroll / will-change-transform", description: "will-change" },
    ],
  },
  {
    title: "SVG",
    slug: "svg",
    entries: [
      { class: "fill-red-500 / fill-current / fill-none", description: "fill" },
      { class: "stroke-red-500 / stroke-current", description: "stroke" },
      { class: "stroke-0 / stroke-1 / stroke-2", description: "stroke-width" },
    ],
  },
  {
    title: "Accessibility",
    slug: "accessibility",
    entries: [
      { class: "sr-only / not-sr-only", description: "visually hide while keeping content for screen readers" },
      { class: "forced-color-adjust-auto / forced-color-adjust-none", description: "forced-color-adjust (Windows High Contrast Mode)" },
    ],
  },
  {
    title: "Responsive breakpoints",
    slug: "responsive",
    entries: [
      { class: "sm: (≥40rem / 640px)", description: "small screens and up" },
      { class: "md: (≥48rem / 768px)", description: "medium screens and up" },
      { class: "lg: (≥64rem / 1024px)", description: "large screens and up" },
      { class: "xl: (≥80rem / 1280px)", description: "extra-large screens and up" },
      { class: "2xl: (≥96rem / 1536px)", description: "2x extra-large screens and up" },
      { class: "max-sm: / max-md: / max-lg: / max-xl: / max-2xl:", description: "applies below that breakpoint (stack with a lower prefix for a range, e.g. md:max-lg:)" },
      { class: "min-[475px]: / max-[600px]:", description: "arbitrary breakpoint values" },
    ],
  },
  {
    title: "Container queries",
    slug: "container-queries",
    entries: [
      { class: "@container / @container/name", description: "mark an element as a query container (optionally named)" },
      { class: "@xs ... @7xl:", description: "style based on container width instead of viewport (@sm:flex-row)" },
      { class: "@max-sm: / @min-[475px]:", description: "max-width / arbitrary container query variants" },
      { class: "@sm/name: / @max-md/name:", description: "target a specific named ancestor container" },
    ],
  },
  {
    title: "State variants",
    slug: "state-variants",
    entries: [
      { class: "hover: / focus: / active: / visited:", description: "interaction states" },
      { class: "focus-within: / focus-visible:", description: "focus states for parent / keyboard-only focus" },
      { class: "disabled: / required: / invalid: / checked:", description: "form states" },
      { class: "first: / last: / odd: / even: / only:", description: "structural pseudo-classes" },
      { class: "group-hover: / group-focus:", description: "style based on a parent with the group class" },
      { class: "peer-checked: / peer-focus:", description: "style based on a sibling with the peer class" },
      { class: "has-[:checked]: / has-checked:", description: ":has() — style based on a descendant's state" },
      { class: "not-hover: / not-disabled:", description: ":not() — style when a state does NOT apply" },
      { class: "dark:", description: "dark mode (based on prefers-color-scheme or a class strategy)" },
      { class: "before: / after: / placeholder: / selection: / file:", description: "pseudo-elements" },
      { class: "starting:", description: "@starting-style — enter/exit transitions without JS" },
    ],
  },
];

// A short, high-frequency subset for the 1-2 page condensed printable version.
export const CONDENSED_GROUPS: CheatGroup[] = [
  {
    title: "Spacing & Sizing",
    slug: "spacing-sizing",
    entries: [
      { class: "p-4 / px-4 / py-4 / pt-4 / pr-4 / pb-4 / pl-4", description: "padding" },
      { class: "m-4 / mx-auto / my-4 / -mt-4", description: "margin" },
      { class: "gap-4 / gap-x-4 / gap-y-4", description: "flex/grid gap" },
      { class: "w-full / w-1/2 / w-64 / size-8", description: "width / width+height" },
      { class: "h-full / h-screen / h-dvh", description: "height" },
      { class: "max-w-2xl / min-h-screen", description: "min/max constraints" },
    ],
  },
  {
    title: "Flexbox & Grid",
    slug: "flexbox-grid",
    entries: [
      { class: "flex / flex-col / flex-wrap", description: "container direction / wrap" },
      { class: "items-center / justify-between / justify-center", description: "alignment" },
      { class: "flex-1 / grow / shrink-0", description: "child sizing" },
      { class: "grid grid-cols-3 gap-4", description: "basic grid" },
      { class: "col-span-2 / row-span-2", description: "spanning" },
      { class: "divide-y / divide-x / divide-gray-200", description: "border between list/menu children" },
    ],
  },
  {
    title: "Typography",
    slug: "typography",
    entries: [
      { class: "text-sm / text-base / text-lg / text-xl / text-2xl", description: "font size" },
      { class: "font-normal / font-medium / font-semibold / font-bold", description: "font weight" },
      { class: "text-center / text-left / text-right", description: "alignment" },
      { class: "leading-tight / leading-normal / leading-relaxed", description: "line height" },
      { class: "truncate / line-clamp-2", description: "text overflow" },
      { class: "text-gray-500 / text-black/60", description: "color + opacity" },
    ],
  },
  {
    title: "Backgrounds & Borders",
    slug: "backgrounds-borders",
    entries: [
      { class: "bg-white / bg-gray-100 / bg-blue-500", description: "background color" },
      { class: "border / border-2 / border-gray-200", description: "border width / color" },
      { class: "rounded-lg / rounded-full / rounded-t-lg", description: "border radius (v4 renamed scale)" },
      { class: "shadow-sm / shadow-md / shadow-lg", description: "box shadow (v4 renamed scale)" },
      { class: "bg-slate-500 / text-red-600 / border-emerald-400", description: "color name + shade (50-950) works on any bg-/text-/border-" },
    ],
  },
  {
    title: "States & Responsive",
    slug: "states-responsive",
    entries: [
      { class: "hover: / focus: / disabled: / dark:", description: "state & theme variants" },
      { class: "sm: / md: / lg: / xl: / 2xl:", description: "responsive prefixes (mobile-first, min-width)" },
      { class: "group-hover: / peer-checked:", description: "parent/sibling-driven states" },
    ],
  },
  {
    title: "Positioning & Display",
    slug: "positioning-display",
    entries: [
      { class: "block / hidden / flex / grid", description: "display" },
      { class: "relative / absolute / inset-0 / top-0", description: "positioning" },
      { class: "z-10 / z-50", description: "stacking order" },
      { class: "overflow-hidden / overflow-auto", description: "overflow" },
      { class: "object-cover / object-contain / object-center", description: "image/video fit & position" },
    ],
  },
  {
    title: "Effects & Transitions",
    slug: "effects-transitions",
    entries: [
      { class: "opacity-0 / opacity-50 / opacity-100", description: "opacity" },
      { class: "transition / duration-200 / ease-in-out", description: "animate a property change" },
      { class: "ring-2 / ring-offset-2 / ring-blue-500", description: "focus / outline ring" },
      { class: "backdrop-blur-sm / backdrop-brightness-90", description: "backdrop filters (overlays, modals)" },
    ],
  },
  {
    title: "Transforms & Interactivity",
    slug: "transforms-interactivity",
    entries: [
      { class: "scale-105 / rotate-45 / -rotate-6", description: "scale & rotate" },
      { class: "translate-x-2 / -translate-y-1", description: "translate" },
      { class: "cursor-pointer / cursor-not-allowed", description: "cursor" },
      { class: "select-none / pointer-events-none", description: "text selection / click-through" },
    ],
  },
];
